# SP via class imbalance

Example [test scores](https://www.brookings.edu/blog/social-mobility-memos/2015/07/29/when-average-isnt-good-enough-simpsons-paradox-in-education-and-earnings/)


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt

In [102]:
t = np.linspace(0,50,11)
count_rate = np.asarray([1,1.5,1.4])
count_pow = np.asarray([1,1.4, 1.3])
count_0 = np.asarray([100,60,40])
count = np.asarray([count_0 + count_rate*(t_i**count_pow) for t_i in t])
share = count/np.asarray([np.sum(count, axis=1)]*3).T
score_rate = np.asarray([.1, .2, .5])
score_0 = [310,290,280]
scores = np.asarray([score_0 + score_rate*t_i for t_i in t])
total_score = np.sum(scores*share,axis=1)





In [103]:
total_score

array([298.        , 297.98576427, 297.85774377, 298.01001517,
       298.44310403, 299.10242414, 299.9344146 , 300.89673092,
       301.95780693, 303.09445576, 304.28961625])

In [104]:
count

array([[100.        ,  60.        ,  40.        ],
       [105.        ,  74.27740454,  51.34459618],
       [110.        ,  97.67829647,  67.93367241],
       [115.        , 126.46898113,  87.320211  ],
       [120.        , 159.43362052, 108.78076946],
       [125.        , 195.89618694, 131.92847315],
       [130.        , 235.41269284, 156.51602682],
       [135.        , 277.66395751, 182.36934708],
       [140.        , 322.40689775, 209.35812014],
       [145.        , 369.4487825 , 237.38052672],
       [150.        , 418.63218742, 266.3544523 ]])

In [105]:
scores

array([[310. , 290. , 280. ],
       [310.5, 291. , 282.5],
       [311. , 292. , 285. ],
       [311.5, 293. , 287.5],
       [312. , 294. , 290. ],
       [312.5, 295. , 292.5],
       [313. , 296. , 295. ],
       [313.5, 297. , 297.5],
       [314. , 298. , 300. ],
       [314.5, 299. , 302.5],
       [315. , 300. , 305. ]])